services:
  - type: web
    name: MusicAPPAPI
    env: php
    plan: free
    buildCommand: "composer install && npm install && npm run prod && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_KEY
        value: base64:YOUR_APP_KEY
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://musicappapi-owkb.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
      - key: MUSIXMATCH_API_KEY
        value: "6a5fa0b7ea788d0d6b94d4ce3263eb68"
