version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: your-database-name
            MYSQL_USER: your-database-username
            MYSQL_PASSWORD: your-database-password
            MYSQL_ROOT_PASSWORD: your-database-root-password
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql-data:
