services:
  - type: web
    name: my-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php-fpm"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromDatabase: true
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: https://musicappapi-mr67.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password

